### PR TITLE
fix: toggle save/reset buttons depending on value

### LINKED ISSUE #1113: Editor options bug
### What is the problem?
The editor options are lost when saved without modification.

### How to reproduce it?
1. Open the Settings page.
2. Expand the advanced options.
3. Click ‘Save’ in the ‘Editor’ section directly.

### What is the expected result?
No options should be changed.

### What is the actual result?
The input area displays `null` and user options are lost.

https://github.com/violentmonkey/violentmonkey/blob/44d1ffbb602d087c1d5fb9c4278bd14892957483/src/common/ui/setting-text.vue#L40
The problem seems to be that `parseJson` is not invoked until the input area is changed.

### Environment
- Browser: Firefox
- Browser version: 83.0
- Violentmonkey version: 2.12.7
- Violentmonkey [pre-release behavior](https://github.com/violentmonkey/violentmonkey/releases): 2.12.7.18
- OS: Windows

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1113.

### CODE REVIEW

File: src/common/ui/setting-text.vue [hunk 1]
```diff
@@ -23,39 +32,70 @@ export default {
...
-      try {
-        this.jsonValue = JSON.parse(this.value);
-        this.error = null;
-      } catch (e) {
-        this.error = e.message || e;
+    /** `event` is absent when calling from save() */
+    onChange(event) {
+      if (!this.error) {
+        const value = this.json ? this.jsonValue : this.value;
+        if (this.sync || !event) options.set(this.name, value);
```
Comment (gera2ld) [inline src/common/ui/setting-text.vue:85]: Is this line virtually `onSave`?

File: src/common/ui/setting-text.vue [hunk 2]
```diff
@@ -23,39 +32,70 @@ export default {
...
-      if (this.error) return;
-      const value = this.json ? this.jsonValue : this.value;
-      if (this.sync) options.set(this.name, value);
-      this.$emit('change', value);
+    onInput(val) {
+      this.canSave = this.hasSave && !this.error && !deepEqual(val, this.savedValue || '');
+      this.canReset = this.hasReset && !deepEqual(val, this.defaultValue || '');
+    },
+    onSave() {
+      if (this.onChange()) this.$emit('save');
```
Comment (gera2ld) [inline src/common/ui/setting-text.vue:95]: Why is `onChange` called here? I think data should have been updated when `save` is emitted.

**Review by gera2ld — CHANGES_REQUESTED** [review]

File: src/common/ui/setting-text.vue (hunk 1 above)
Comment (tophf) [reply src/common/ui/setting-text.vue:85]: onSave does nothing except sending an event to the parent, which is why it calls onChange to actually write the value.

File: src/common/ui/setting-text.vue (hunk 2 above)
Comment (tophf) [reply src/common/ui/setting-text.vue:95]: It's for deduplication. The only purpose of a dedicate onSave method is to inform the parent so it could do something. I guess I can extract the actual saving into a separate method to reduce confusion.

Comment (tophf) [reply src/common/ui/setting-text.vue:95]: BTW, saving is performed automatically when the text field loses focus, so there's no need for the save button strictly speaking, we could do without it by using an indicator for unsaved state and `beforeunload` listener to prevent the loss of data.

Comment (tophf) [reply src/common/ui/setting-text.vue:95]: Extraction example:
```js
    onChange() {
      this.commit({ change: true });
    },
    onInput(val) {
      this.canSave = this.hasSave && !this.error && !deepEqual(val, this.savedValue || '');
      this.canReset = this.hasReset && !deepEqual(val, this.defaultValue || '');
    },
    onSave() {
      if (this.commit({ save: true })) {
        this.$emit('save');
      }
    },
    onReset() {
      options.set(this.name, this.defaultValue);
    },
    commit({ change, save }) {
      if (!this.error) {
        const value = this.json ? this.jsonValue : this.value;
        if (this.sync || save) options.set(this.name, value);
        if (change) this.$emit('change', value);
        return true;
      }
    },
```

Comment (gera2ld) [reply src/common/ui/setting-text.vue:95]: We can update data on `input` and save/sync on `change`.
A simple way to handle `click` of save button is to wrap in `setTimeout` and avoid calling `change` manually.

Comment (gera2ld) [reply src/common/ui/setting-text.vue:95]: > BTW, saving is performed automatically when the text field loses focus, so there's no need for the save button strictly speaking, we could do without it by using an indicator for unsaved state and `beforeunload` listener to prevent the loss of data.

Good idea, maybe showing a different border color or some icon for unsaved state is enough.

Comment (tophf) [reply src/common/ui/setting-text.vue:95]: > update data on input

What data?

> setTimeout 

It can be argued that an indirect approach isn't better than a direct call but maybe I didn't understand what exactly you mean.

Comment (gera2ld) [reply src/common/ui/setting-text.vue:95]: `data` refers to `this.jsonValue` here, which is not updated in time when the textarea is focused and save button is clicked.

`setTimeout` can be replaced with `this.$nextTick` here, to wait until reactive data is updated. In this way it does not need to call something that should not be done by it.

```js
onSave() {
  this.$nextTick(() => {
     // do stuff
  });
}
```

**Comment by gera2ld** [comment]
The save button seems to do nothing indeed. 😅 The `sync` prop is never used.

File: src/common/ui/setting-text.vue (hunk 2 above)
Comment (tophf) [reply src/common/ui/setting-text.vue]: I've simplified the code by removing `sync`, see if you like it now. As for removing the save button, let's keep it so people don't get nervous :-) and anyway it's also useful as an obvious and understandable indicator of the modified state.

P.S. there was a problem in `master` fixed by 9fc8b6b2 - on browser startup (when "restore previous session" is selected in browser options) the Violentmonkey dashboard didn't initialize properly in the active tab.

**Comment by gera2ld** [comment]
It should work but not quite Vue-flavor. I'll merge it now and try to see if I can polish it later.
