### PR TITLE
fix: GoogleDrive auth in Edge

### LINKED ISSUE #815: Chromium Edge: Stuck on authorizing Google Drive
# What is the problem?

Cannot sync scripts from Google Drive with Chromium based Edge.

### How to reproduce it?
1. Select Google Drive and click Authorize.
2. Grant the access from the popup page. 

### What is the expected result?

It should start syncing.

### What is the actual result?

It kept showing "Authorizing".

This log seems to relevant:
```
index.html:1 Uncaught (in promise) Object
index.js:1 POST https://www.googleapis.com/oauth2/v4/token 400
(anonymous) @ common.js:1
g @ common.js:1
(anonymous) @ index.js:1
Promise.then (async)
loadData @ index.js:1
authorized @ index.js:1
checkAuth @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
index.html:1 Uncaught (in promise) {url: "https://www.googleapis.com/oauth2/v4/token", data: {…}, xhr: XMLHttpRequest, status: 400}
Promise.then (async)
checkAuth @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
```
```json
{error: "invalid_grant", error_description: "Malformed auth code."}
```

[xhr_token.har.txt](https://github.com/violentmonkey/violentmonkey/files/4082245/xhr_token.har.txt)

### Environment
- Browser: Edge 
- Browser version: 79.0.309.68 (Official build) (64-bit)
- Violentmonkey version: 2.12.4
- OS: Windows 10 18363

### PR DESCRIPTION
**Pull request by tophf**
Fixes #815.

### CODE REVIEW

File: src/background/sync/googledrive.js [hunk 1]
```diff
@@ -125,7 +125,7 @@ const GoogleDrive = BaseService.extend({
     if (url.startsWith(redirectUri)) {
       this.authState.set('authorizing');
       this.authorized({
-        code: url.split('#')[0].slice(redirectUri.length),
+        code: decodeURIComponent(url.split('#')[0].slice(redirectUri.length)),
```
Comment (gera2ld) [inline src/background/sync/googledrive.js]: Is this safe for other browsers?

Comment (tophf) [reply src/background/sync/googledrive.js]: I've verified it works in Chrome, yes.

Comment (tophf) [reply src/background/sync/googledrive.js]: Actually I'm surprised the old code worked...

Comment (gera2ld) [reply src/background/sync/googledrive.js]: Works in Firefox too.

Comment (gera2ld) [reply src/background/sync/googledrive.js]: > Actually I'm surprised the old code worked... because I would have expected that URL parameters are always encoded.

That's true. 🤣
