### PR TITLE
fix: GM_setClipboard in FF

### LINKED ISSUE #685: GM_setClipboard() has stopped working
### What is the problem?
I feel like GM_setClipboard() has stopped working.
Is this a bug or is this the intended specification?
Personally, I hope GM_setClipboard() will be kept.

### How to reproduce it?
1.use GM_setClipboard("foo") in any userscript

### What is the expected result?
foo is copied to the clipboard

### What is the actual result?
Nothing happens

### Environment
- Browser: Firefox Dev x64
- Browser version: 71.0b7
- Violentmonkey version: 2.12.0
- OS: Windows7 x64

### PR DESCRIPTION
**Pull request by tophf**
Fixes #685.

In addition to a bug in my implementation (preventDefault and stopImmediatePropagation should be picked from Event.prototype) there's apparently a bug/quirk in Firefox which prevents the entire setClipboard+onCopy hack from working when ::safe calls are used. ~I guess Firefox somehow changes the initial methods or it uses a Proxy internally on `document` specifically. It's a mystery for me because in other parts of the content script the similar safe calls work correctly with `window::addEventListener` and `document::getReadyState`.~ 

Turns out there was another bug in my code + old versions of FF define execCommand in document.__proto__ not in Document.prototype...

### CODE REVIEW

**Comment by tophf** [comment]
Interestingly, different versions of FF seem to fail in different parts of the code even when it's fixed to use the correct source for preventDefault and stopImmediatePropagation, which reinforces my guess it's a bug or an internal quirk of FF.

File: src/injected/content/clipboard.js [hunk 1]
```diff
@@ -1,13 +1,8 @@
 import { isFirefox } from '#/common/ua';
 import { sendCmd } from '../utils';
-import { addEventListener, logging } from '../utils/helpers';
+import { logging } from '../utils/helpers';
 import bridge from './bridge';
 
-const { execCommand } = Document.prototype;
-const { setData } = DataTransfer.prototype;
-const getClipboardData = Object.getOwnPropertyDescriptor(ClipboardEvent.prototype, 'clipboardData').get;
-const { preventDefault, removeEventListener, stopImmediatePropagation } = EventTarget.prototype;
```
Comment (gera2ld) [inline src/injected/content/clipboard.js]: The real problem is, `preventDefault` and `stopImmediatePropagation` comes from `Event.prototype`. I corrected it locally and it worked in Firefox!

Comment (gera2ld) [reply src/injected/content/clipboard.js]: Sorry, there is one more thing. The getter `clipboardData` should also be kept.

**Comment by gera2ld** [comment]
I am wondering whether it's safe to transform getters into functions and call them on the original objects. I think this may involve some implementation details of browsers. Maybe we should skip guarding the getters?

File: src/injected/content/clipboard.js [hunk 2]
```diff
@@ -23,18 +18,20 @@ bridge.addHandlers({
...
 
+// not using ::safe calls as it mysteriously doesn't work here in FF (probably a bug)
+
 function onCopy(e) {
-  e::stopImmediatePropagation();
-  e::preventDefault();
+  e.stopImmediatePropagation();
+  e.preventDefault();
   const { type, data } = clipboardData;
-  e::getClipboardData::setData(type || 'text/plain', data);
```
Comment (gera2ld) [inline src/injected/content/clipboard.js]: It should be `e::getClipboardData()` instead of `e::getClipboardData` here.

Comment (tophf) [reply src/injected/content/clipboard.js]: Gee, I **really** can be blind, but this still doesn't help in Firefox ESR: like I explained above FF fails in different places and ESR won't even run the onCopy listener with document::addEventListener, only with document.addEventListener

Comment (tophf) [reply src/injected/content/clipboard.js]: Eek, FF ESR defines `execCommand` in `document.__proto__` not in `Document.prototype`...

File: src/injected/content/clipboard.js [hunk 3]
```diff
@@ -3,10 +3,13 @@ import { sendCmd } from '../utils';
 import { addEventListener, logging } from '../utils/helpers';
 import bridge from './bridge';
 
-const { execCommand } = Document.prototype;
+// some old versions of Firefox define it on __proto__
+// eslint-disable-next-line no-proto
+const execCommand = Document.prototype.execCommand || document.__proto__.execCommand;
```
Comment (gera2ld) [inline src/injected/content/clipboard.js]:
```
document
  |
HTMLDocument - (Firefox ESR) execCommand
  |
Document - (Chrome and newer Firefox) execCommand
```

So we can just read `execCommand` from `HTMLDocument.prototype` or even `document` since `document` cannot be modified at `document-start`.

Comment (tophf) [reply src/injected/content/clipboard.js]: Yeah, good idea.
