### PR TITLE
fix: group multiple update notifications in one

### LINKED ISSUE #1228: [UX/UI] Too many notifications when there are a lot of errors updating scripts
### What is the problem?

Sometimes (I have no idea why and when, probably my ISP is the reason) VM fails to update all the installed script. And with this it shows a lot of notifications like this:

image

These notifications occupy the whole vertical space (cause there are many of them), and if some links to the script are long - they occupy a lot of horizontal space too, making around of 40% browser window hidden.

### How to reproduce it?

I guess you need to call a lot of notifications https://github.com/violentmonkey/violentmonkey/blob/e8177755f1af05a2d47ac5e1eb8a51f6c66be0ad/src/background/utils/message.js#L5 at once (let's say 30) 

### What is the expected result?

The notifications are shown with delay, one by one (or small groups 2-3 message each), not blowing the screen. Or maybe VM should not update (when it does it automatically) all the scripts at once.

### What is the result in the [upcoming release](https://github.com/violentmonkey/violentmonkey/releases)?

Didn't test

### Environment
- Browser: Firefox 86.0.1 (64-bit)
- Violentmonkey version: v2.12.11
- OS: Win 8.1 x64

### PR DESCRIPTION
**Pull request by tophf**
Fixes #1228.

### CODE REVIEW

File: src/background/utils/notifications.js [hunk 1]
```diff
@@ -1,18 +1,20 @@
...
 Object.assign(commands, {
   /** @return {Promise<string>} */
-  async Notification(data, src, bgExtras) {
+  async Notification(data, src, bgExtras = {}) {
+    const { items, onClick, type } = bgExtras;
     const notificationId = await browser.notifications.create({
-      type: 'basic',
-      title: data.title || i18n('extName'),
+      type: type || 'basic',
+      title: data.title || '',
```
Comment (tophf) [inline src/background/utils/notifications.js:12]: I removed the default title because Chrome/FF already displays "Violentmonkey" in the non-customizable header of the notification.

**Review by gera2ld — APPROVED** [review]
